[package]
name = "ls-clone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nerd-font-symbols = "0.1.0"
colored = "2"
temp-dir = "0.1.12"

